---
- name: test
  gather_facts: false
  hosts: webservers
  vars:
    ansible_ssh_user: sysadmin
  become: yes

  pre_tasks:
    - name: Validating the ssh port is open and
      wait_for:
        host: '{{ ansible_host }}'
        port: 22
        delay: 10
        timeout: 300
        state: started
        search_regex: OpenSSH

  tasks:
     - name: Install Nginx Web Server on Debian Family
       apt:
         name:
          - nginx
         state: latest
         update_cache: yes